### ISSUE TITLE
Why not use l4lb instead?

### ISSUE THREAD

**Issue by jmparraguez-haulmer** [Mashape/kong-dist-dcos#3]
I see that you use marathon as lb between kong and the bd postgres, why not use instead l4lb (minuteman)?

**Comment by shashiranjan84** [comment]
@jmparra here provided templates are just to help you setup Kong in DCOS. You can always update it or use different stack to suit your need.  Also feel free to send us PR, we would love to add it after review.

**Comment by shashiranjan84** [comment]
@jmparra indeed `VIPs` is better option for E/W traffic. I have updated the template.
