### ISSUE TITLE
Next steps after the deployment

### ISSUE THREAD

**Issue by julienstroheker** [Mashape/kong-dist-dcos#4]
I think it would be helpful to have few more steps at the end, with one  application example. 

It is confusing on how we have to set up our application running on DCOS with Kong and Marathon-lb.

For example, do we still need to tag our app with the labels: 
*  "HAPROXY_GROUP"
*  "HAPROXY_0_VHOST"
*  "HAPROXY_0_MODE"

External or Internal GROUP ?

Do we have to expose Kong outside the cluster by adding a `HAPROXY_0_VHOST` label ?

Thanks

**Comment by thibaultcha** [comment]
Thanks @julienstroheker. What do you think @shashiranjan84?

**Comment by shashiranjan84** [comment]
@julienstroheker provided DCOS solution is just to help you Kong up and running. You can always change it to suit your needs. All the questions you asked are very subjective and may have different answer based on use case. I would also advise going though the [DC/OS](https://docs.mesosphere.com/1.8/overview/), [Marathon](https://mesosphere.github.io/marathon/), and [Marathon-lb](https://docs.mesosphere.com/1.7/usage/service-discovery/marathon-lb/usage/) docs.

I will also try to update the doc with Kong setup with a demo application.

**Comment by julienstroheker** [comment]
"`I will also try to update the doc with Kong setup with a demo application.`"

Would be great ! Thanks
